### ISSUE TITLE
Regression testing for Excel interface

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#472]
We're running the Excel interface without any regression testing.  There do appear to be some ways to regression test on VBA scripts, however, so we should set up a way to try to do that.

Some possible pointers:
https://stackoverflow.com/questions/4547487/how-to-unit-test-excel-vba-code

**Comment by coverney** [comment]
Some more references:
- https://rubberduckvba.wordpress.com/2017/10/19/how-to-unit-test-vba-code/
- https://github.com/rubberduck-vba/Rubberduck/wiki/Unit-Testing
- https://www.bernardvukas.com/testing/tutorial-excel-vba-unit-testing/

**Comment by coverney** [comment]
Updates:
- I sent an email to Rubberduck to ask them if we can run it headless
- I was able to get the unit testing tutorial working without the TASBE VBA code
- I slowly integrated in the old VBA code and wrote some basic unit tests (i.e. update filename and update plates)

However, when I tried to add in a helper function I use to copy the Batch CSV data into the results sheet, I got the following error from Rubberduck that I have no idea how to approach:
`
2019-07-14 13:53:29.4589;ERROR-2.4.1.4627;Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase;Exception thrown resolving 'VBAProject.AnalysisMethods' (thread 11).;System.InvalidCastException: Unable to cast object of type 'WhitespaceIndexExprContext' to type 'IndexExprContext'.
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(RedimStmtContext context) in C:\projects\rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 261
   at Rubberduck.Parsing.Grammar.VBAParser.RedimStmtContext.EnterRule(IParseTreeListener listener) in C:\projects\rubberduck\Rubberduck.Parsing\obj\Release\net46\VBAParser.cs:line 11082
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.ReferenceManagement.ReferenceResolveRunnerBase.ResolveReferences(DeclarationFinder finder, QualifiedModuleName module, IParseTree tree, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ReferenceManagement\ReferenceResolveRunnerBase.cs:line 251
`
I am also not sure what to do about the msg boxes that pop up when testing (i.e. a "Filenames Updated" message appears after the user presses the update filenames button and the function completes). Currently I just manually deal with them. We could add in a variable that only displays the msg boxes if it isn't in testing mode?

**Comment by jakebeal** [comment]
In terms of the message boxes --- turning them off for testing is fine.  In Matlab/Octave, I turn off the actual output of figures during testing mode too, since it has issues running in the headless environment on travis.

As for the other error... if you're blocked, see if you can get help from RubberDuck and work on other issues in the mean time.

**Comment by jakebeal** [comment]
Looks like rubberduck won't be able to be used on travis-ci, since it requires an active Office installation. This probably means that nothing can operate on travis for Excel VBA testing.

We might still be able to have people test locally (just not in a CI manner).  There are still some issues with getting rubberduck to run the code.

**Comment by coverney** [comment]
I got this reply from the issue thread I opened: https://github.com/TASBE/TASBEFlowAnalytics-Tutorial/pull/71

**Comment by coverney** [comment]
I was able to fix the old error I had with running the Rubberduck unit test. If we decide to continue using Rubberduck even though it can't run headless, then I can add more unit tests.

**Comment by jakebeal** [comment]
I think that we should, indeed, keep using Rubberduck, and just make the manual testing part of the regular workflow.

**Comment by coverney** [comment]
Sounds good. I am already working on incorporating the Matlab aspects to rubberduck, which will hopefully work once I fix some Matlab licensing problems.
